# Generated by Django 3.2.18 on 2023-04-23 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fortress', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stage',
            name='target',
        ),
        migrations.RemoveField(
            model_name='stageinfo',
            name='target',
        ),
        migrations.AddField(
            model_name='stage',
            name='targets',
            field=models.ManyToManyField(to='fortress.Target'),
        ),
        migrations.AddField(
            model_name='stageinfo',
            name='targets',
            field=models.ManyToManyField(to='fortress.Target'),
        ),
    ]
